### PR TITLE
Adding support for Chinese simplified (zh_CN)

### PR DESCRIPTION
**Pull request by xiangming**

### CODE REVIEW

**Comment by astik** [comment]
Here are the translations we are using for Chinese simplified (we add numbers) :

```js
zh_CN = {
	wordSeparator: '',
	prefixAgo: null,
	prefixFromNow: null,
	suffixAgo: '前',
	suffixFromNow: '后',
	seconds: '少于一分钟',
	minute: '一分钟',
	minutes: '%d分钟',
	hour: '一小时',
	hours: '%d小时',
	day: '一日',
	days: '%d日',
	month: '一个月',
	months: '%d个月',
	year: '一年',
	years: '%d年',
	numbers: [
		'零',
		'一',
		'二',
		'三',
		'四',
		'五',
		'六',
		'七',
		'八',
		'九',
		'十',
		'十一',
		'十二',
		'十三',
		'十四',
		'十五',
		'十六',
		'十七',
		'十八',
		'十九',
		'二十',
		'二十一',
		'二十二',
		'二十三',
		'二十四',
		'二十五',
		'二十六',
		'二十七',
		'二十八',
		'二十九',
		'三十',
		'三十一',
		'三十二',
		'三十三',
		'三十四',
		'三十五',
		'三十六',
		'三十七',
		'三十八',
		'三十九',
		'四十',
		'四十一',
		'四十二',
		'四十三',
		'四十四',
		'四十五',
		'四十六',
		'四十七',
		'四十八',
		'四十九',
		'五十',
		'五十一',
		'五十二',
		'五十三',
		'五十四',
		'五十五',
		'五十六',
		'五十七',
		'五十八',
		'五十九',
		'六十',
		'六十一',
		'六十二',
		'六十三',
		'六十四',
		'六十五',
		'六十六',
		'六十七',
		'六十八',
		'六十九',
		'七十',
		'七十一',
		'七十二',
		'七十三',
		'七十四',
		'七十五',
		'七十六',
		'七十七',
		'七十八',
		'七十九',
		'八十',
		'八十一',
		'八十二',
		'八十三',
		'八十四',
		'八十五',
		'八十六',
		'八十七',
		'八十八',
		'八十九',
		'九十',
		'九十一',
		'九十二',
		'九十三',
		'九十四',
		'九十五',
		'九十六',
		'九十七',
		'九十八',
		'九十九',
		'一百'
	]
};
```

**Comment by xiangming** [comment]
@astik When will we use these numbers? I think we can ignore it.

BTW. In China, we use: 

”1分钟“ more than ”一分钟“,
”1小时“ more than ”一小时“
and so no

**Comment by astik** [comment]
Those numbers are used to replace %d into the translation.

**Comment by xiangming** [comment]
@astik You are doing it in Chinese Traditional way, not Chinese simplified.

In Chinese simplified, better to use Arabic numerals.

**Comment by yaru22** [comment]
I'm not Chinese but I agree with @xiangming. I think using Arabic numerals would be better. I should've noticed that for `zh_TW` as well. @astik, do you agree with @xiangming? If so, could you make the necessary changes?

**Comment by vdelacou** [comment]
Yes I agree, maybe we can try to put both version so people can decide:)

**Comment by xiangming** [comment]
@yaru22 I think you can merge this PR.

**Comment by yaru22** [comment]
Oops, looking back at my comment, I mistakenly thought @astik was the author of this PR. Sorry about that @xiangming. Merging this PR now.

**Pull request merged**
