### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by astik**
This should add Travis as continuous integration platform.
(WIP)

### CODE REVIEW

**Comment by astik** [comment]
To prepare this, @yaru22, can you add angular-timeago to the travis platform (https://travis-ci.org/) ?

**Comment by astik** [comment]
A test is making the CI inconsistent as it is depending on time comparing :

```javascript
  it('accept Date object', function () {
    var nowDate = new Date();
    var nowDateString = ngDateFilter(nowDate, 'yyyy-MM-dd HH:mm');
    expect(filter(nowDate)).to.equal(filter(nowDateString));
  });
```

For the nowDateString variable, seconds are not used. So that the test result will depend on when the test is executed.

If it executed before the 45th sec of the current minute, it will be ok :

- nowDate : x seconds which is lesser than 45
- nowDateString : 0 second is lesser than 45
- test is ok

If it is executed after the 45th sec of the current minute, it will be ko :

- nowDate : x seconds which is greater than 45
- nowDateString : 0 second is lesser than 45
- test is ko

So that, I'm adding seconds to the string pattern :

```javascript
  it('accept Date object', function () {
    var nowDate = new Date();
    var nowDateString = ngDateFilter(nowDate, 'yyyy-MM-dd HH:mm:ss');
    expect(filter(nowDate)).to.equal(filter(nowDateString));
  });
```

**Comment by astik** [comment]
@yaru22 , you'll be able to easily activate travis for this project by going to https://travis-ci.org/yaru22/angular-timeago.
You can check what it looks like here : https://travis-ci.org/astik/angular-timeago
I will delete my repo (and my travis) after activation or your namespace =)

**Comment by yaru22** [comment]
@astik, thanks for merging it in =) This looks grea! I just activated https://travis-ci.org/yaru22/angular-timeago.

**Pull request merged**
