### PR TITLE
Added support for momentjs objects

### PR DESCRIPTION
**Pull request by Maximaximum**
Fixes https://github.com/yaru22/angular-timeago/issues/78

### CODE REVIEW

**Comment by astik** [comment]
@Maximaximum, are you familar with using git to [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the commits in your PR? If so, can you do this, it would be cleaner to have a proper commit for the modification.

**Comment by Maximaximum** [comment]
@astik Yeah, I'm just trying to do that right now. I'm really far from being a git pro, so this might take some time. I'll notify you when I'm done. Thanks!

**Comment by astik** [comment]
(to be honest, i was just like you before and someone post this exact message I copy paste to you =D)

**Comment by Maximaximum** [comment]
@astik I'm done, you can accept the PR now.

**Pull request merged**
